# title: "Cathrine Shalby"
# description: "Cybersecurity Professional"
theme: minima
# author: Cathrine Shalby
# email: cathrinehassan@gmail.com
# social_links:
#   linkedin: https://linkedin.com/in/cathrineshalby
#   instagram: https://instagram.com/rawshrimps
